###

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@gmail.com",
  "password": "12345678"
}

###

GET http://localhost:3333/users/e9d42a1e-13cd-45ad-ba2e-9a572a33d190
Content-Type: application/json

###

GET http://localhost:3333/users
Content-Type: application/json